
spring:
  datasource:
    url: jdbc:mysql://10.83.16.43:3306/asset_status_test10?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: zU!ykpx3EG)$$1e6
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver


rocketmq:
  name-server: 10.83.0.81:9876
  producer:
    group: ${spring.application.name}
    topic:
      file01topic: file01topic-dev
      file02topic: file02topic-dev
      file03topic: file03topic-dev
      file04topic: file04topic-dev
      file05topic: file05topic-dev
      file05abstopic: file05abstopic-dev
      file06topic: file06topic-dev
      file07topic: file07topic-dev
      file08topic: file08topic-dev
      file09topic: file09topic-dev
      file10topic: file10topic-dev
      file11topic: file11topic-dev
      file12topic: file12topic-dev
      file13topic: file13topic-dev
  consumer:
    group: ${spring.application.name}
    topic:
      newfile01topic: 00-01-0014-test
      newfile02topic: 00-01-0015-0
      newfile03topic: 00-01-0016-0
      newfile04topic: 00-01-0017-0
      newfile05topic: 00-01-0018-0
      newfile06topic: 00-01-0019-0
      newfile07topic: 00-01-0020-0
      newfile08topic: 00-01-0021-0
      newfile09topic: 00-01-0022-0
      newfile10topic: 00-01-0023-0
      newfile11topic: 00-01-0024-0
      newfile12topic: 00-01-0025-0
      newfile13topic: 00-01-0026-0

test:
  zipPrefix: YXCD_YNXT_QC_
  localDownPath: /Users/clear/asset/test
  localUnzipPath: /Users/clear/asset/test/unzip
  sftp:
    host: 193.112.233.142
    port: 20022
    username: prdgm
    password: 9363hb2TDx4kCqiWALE
    timeout: 30000
